package com.dkim.springmvc.model;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp")
public class Emp implements java.io.Serializable {

	private long pkid;
	private Integer empId;
	private String empName;
	private String empRole;
	private BigDecimal empSalary;

	public Emp() {
	}

	public Emp(long pkid) {
		this.pkid = pkid;
	}

	public Emp(long pkid, Integer empId, String empName, String empRole, BigDecimal empSalary) {
		this.pkid = pkid;
		this.empId = empId;
		this.empName = empName;
		this.empRole = empRole;
		this.empSalary = empSalary;
	}

	@Id

	@Column(name = "pkid", unique = true, nullable = false)
	public long getPkid() {
		return this.pkid;
	}

	public void setPkid(long pkid) {
		this.pkid = pkid;
	}

	@Column(name = "emp_id")
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@Column(name = "emp_name", length = 50)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "emp_role", length = 50)
	public String getEmpRole() {
		return this.empRole;
	}

	public void setEmpRole(String empRole) {
		this.empRole = empRole;
	}

	@Column(name = "emp_salary", precision = 15)
	public BigDecimal getEmpSalary() {
		return this.empSalary;
	}

	public void setEmpSalary(BigDecimal empSalary) {
		this.empSalary = empSalary;
	}

}
