// default package
// Generated 2018. 4. 12 ���� 3:51:31 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AppUser generated by hbm2java
 */
@Entity
@Table(name = "app_user")
public class AppUser implements java.io.Serializable {

	private AppUserId id;

	public AppUser() {
	}

	public AppUser(AppUserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 20)),
			@AttributeOverride(name = "password", column = @Column(name = "password", nullable = false)) })
	public AppUserId getId() {
		return this.id;
	}

	public void setId(AppUserId id) {
		this.id = id;
	}

}
